config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views import defaults as default_views
from django.views.generic import TemplateView

urlpatterns = [
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),

    # Custom url patterns
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^', include('pages.urls', namespace='pages')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

precision/accounts/urls.py
from django.conf.urls import url
from django.contrib.auth.views import (login, logout, logout_then_login,
                                       password_change, password_change_done, password_reset,
                                       password_reset_done, password_reset_confirm, password_reset_complete)

from .views import LoginView, RegisterView

urlpatterns = [

    # Authentication
    # ==============
    url(r'^login/$',
        LoginView.as_view(),
        name='login'
    ),

    url(r'^logout/$',
        logout,
        name='logout'
    ),

    url(r'^logout-then-login/$',
        logout_then_login,
        name='logout_then_login'
    ),

    url(r'^register/$',
        RegisterView.as_view(),
        name='register'
    ),


    # Password Change
    # ===============
    url(r'^password-change/$',
        password_change,
        {'post_change_redirect': 'accounts:password_change_done'},
        name='password_change'
    ),

    url(r'^password-change/done/$',
        password_change_done,
        name='password_change_done'
    ),


    # Password Reset
    # ==============
    url(r'^password-reset/$',
        password_reset,
        {'post_reset_redirect': 'accounts:password_reset_done'},
        name='password_reset'
    ),

    url(r'^password-reset/done/$',
        password_reset_done,
        name='password_reset_done'
    ),

    url(r'^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$',
        password_reset_confirm,
        {'post_reset_redirect': 'accounts:password_reset_complete'},
        name='password_reset_confirm'
    ),

    url(r'^password-reset/complete/$',
        password_reset_complete,
        name='password_reset_complete'
    ),

]

precision/pages/urls.py
from django.conf.urls import url

from .views import HomeView

urlpatterns = [
    url(r'^$', HomeView.as_view(), name='home')
]

precision/accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.utils.translation import ugettext_lazy as _


class SchoolAdministrator(AbstractUser):
    pass

precision/accounts/forms.py
from django import forms
from precision.accounts.models import SchoolAdministrator # absolute import to be fixed


# CODE BELOW THIS LINE IS NOT USED, BUT PRESENT FOR EDUCATION PURPOSES
# ====================================================================
class LoginForm(forms.Form):
    email = forms.CharField(widget=forms.EmailInput)
    password = forms.CharField(widget=forms.PasswordInput)
# ====================================================================


class SchoolAdministratorRegistrationForm(forms.ModelForm):
    password = forms.CharField(label='password', widget=forms.PasswordInput)
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput)

    class Meta:
        model = SchoolAdministrator
        fields = ('email', 'first_name', 'last_name')

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('Passwords do not match!')
        return cd['password2']

precision/accounts/views.py
from django.contrib.auth import authenticate, login
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic.base import TemplateResponseMixin, View

from .forms import LoginForm, SchoolAdministratorRegistrationForm


class LoginView(TemplateResponseMixin, View):
    template_name = 'registration/login.html'

    def get(self, request):
        form = LoginForm()
        context = {'section': 'login', 'form': form}
        return self.render_to_response(context)

    def post(self, request):
        form = LoginForm(request.POST)

        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(email=cd['email'], password=cd['password'])

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponse('Authenticated successfully')
                else:
                    return HttpResponse('Disabled account')
            else:
                return HttpResponse('Invalid login')
        else:
            return redirect('accounts:login')

        
class RegisterView(TemplateResponseMixin, View):
    template_name = 'registration/register.html',

    def get(self, request):
        form = SchoolAdministrationRegistrationForm
        context = {'section': 'register', 'form': form}
        return self.render_to_response(context)

    def post(self, request):
        form = SchoolAdministrationRegistrationForm(request.POST)
        template_name = 'registration/register_done.html'

        if form.is_valid():
            # Create a new administrator but do not save it yet
            new_administrator = form.save(commit=False)

            # Set chosen password
            new_administrator.set_password(form.cleaned_data['password'])

            # Save administrator object
            new_administrator.save()

            context = {'section': 'register', 'new_administrator': new_administrator}
            return render(request, template_name, context)
        else:
            return redirect('accounts:register')

precision/pages/views.py
from django.shortcuts import render
from django.views.generic.base import TemplateResponseMixin, View


class HomeView(TemplateResponseMixin, View):
    template_name = 'pages/home.html'

    def get(self, request):
        context = {'section': 'home'}
        return self.render_to_response(context)

precision/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

precision/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
    <head>

        <!-- Meta Tags  -->
        <meta charset="utf-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">
        <!-- ./ Meta Tags -->

        <!-- Shim-->
        <!--[if lt IE 9]>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
        <![endif]-->
        <!-- ./ Shim -->

        {% block css %}
            <!-- Latest compiled and minified Bootstrap 4 Alpha 4 CSS -->
            <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css">

            <!-- This file stores project-specific CSS -->
            <link href="{% static 'css/project.css' %}" rel="stylesheet">
        {% endblock %}
  </head>

  <body>

    <div class="m-b-1">
      <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'pages:home' %}">project_precision</a>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">

            <li class="nav-item active">
              <a class="nav-link" href="{% url 'pages:home' %}">Home <span class="sr-only">(current)</span></a>
            </li>

          </ul>
        </div>
      </nav>

    </div>

    <!-- Container -->
    <div class="container">

        <!-- Alerts -->
        {% if messages %}
            {% for message in messages %}
                <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}</div>
            {% endfor %}
        {% endif %}
        <!-- ./ Alerts -->

        <!-- Main Content -->
        {% block content %}
        {% endblock content %}
        <!-- ./ Main Content -->

    </Div>
    <!-- ./ Container -->

    <!-- JavaScript -->
    {% block javascript %}
        <!-- Placed at the end of the document so the pages load faster -->

        <!-- Required by Bootstrap v4 Alpha 4 -->
        <script src="https://code.jquery.com/jquery-3.1.1.slim.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"></script>

        <!-- Project specific JavaScript -->
        <script src="{% static 'js/project.js' %}"></script>

    {% endblock javascript %}
    <!-- ./ JavaScript -->
  </body>
</html>
 

precision/templates/bootstrap4/field.html
{% load crispy_forms_field %}

{% if field.is_hidden %}
    {{ field }}
{% else %}
    {% if field|is_checkbox %}
        <div class="form-group{% if using_grid_layout %} row{% endif %}">
        {% if label_class %}
            <div class="controls col-{{ bootstrap_device_type }}-offset-{{ label_size }} {{ field_class }}">
        {% endif %}
    {% endif %}
    <{% if tag %}{{ tag }}{% else %}div{% endif %} id="div_{{ field.auto_id }}" {% if not field|is_checkbox %}class="form-group{% if using_grid_layout %} row{% endif %}{% else %}class="checkbox{% endif %}{% if wrapper_class %} {{ wrapper_class }}{% endif %}{% if form_show_errors%}{% if field.errors %} has-danger{% endif %}{% endif %}{% if field.css_classes %} {{ field.css_classes }}{% endif %}">
        {% if field.label and not field|is_checkbox and form_show_labels %}
            <label for="{{ field.id_for_label }}" class="form-control-label {{ label_class }}{% if field.field.required %} requiredField{% endif %}">
                {{ field.label|safe }}{% if field.field.required %}<span class="asteriskField">*</span>{% endif %}
            </label>
        {% endif %}

        {% if field|is_checkboxselectmultiple %}
            {% include 'bootstrap4/layout/checkboxselectmultiple.html' %}
        {% endif %}

        {% if field|is_radioselect %}
            {% include 'bootstrap4/layout/radioselect.html' %}
        {% endif %}

        {% if not field|is_checkboxselectmultiple and not field|is_radioselect %}
            {% if field|is_checkbox and form_show_labels %}
                <label for="{{ field.id_for_label }}" class="{% if field.field.required %} requiredField{% endif %}">
                    {% crispy_field field %}
                    {{ field.label|safe }}
                    {% include 'bootstrap4/layout/help_text_and_errors.html' %}
                </label>
            {% else %}
                <div class="{{ field_class }}">
                    {% crispy_field field %}
                </div>
                {% include 'bootstrap4/layout/help_text_and_errors.html' %}
            {% endif %}
        {% endif %}
    </{% if tag %}{{ tag }}{% else %}div{% endif %}>
    {% if field|is_checkbox %}
        {% if label_class %}
            </div>
        {% endif %}
        </div>
    {% endif %}
{% endif %}

precision/templates/bootstrap4/layout/field_errors_block.html
{% if form_show_errors and field.errors %}
    {% for error in field.errors %}
        <p id="error_{{ forloop.counter }}_{{ field.auto_id }}" class="text-danger help-block">{{ error }}</p>
    {% endfor %}
{% endif %}

precision/templates/pages/about.html
{% extends "base.html" %}

precision/templates/pages/home.html
{% extends "base.html" %}